on:
  pull_request:
    types:
      - closed
    branches:
      - 'preprod_*'
      - main

jobs:
  preprod-deploy:
    if: ${{ startsWith(github.ref, 'preprod_')  && github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref}} 
      - run: echo The PR was merged to preprod
      - run: sh ./deploy.sh
  prod-deploy:
    if: ${{ github.ref == 'main' && github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref}} 
      - run: echo The PR was merged to master
      - run: ls ${{ github.workspace }}