on:
  pull_request:
    types:
      - closed
    branches:
      - preprod

jobs:
  preprod-deploy:
    if: ${{ github.ref == 'preprod' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was merged
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}