on:
  pull_request:
    types:
      - closed
    branches:
      - preprod

jobs:
  preprod-deploy:
    if: ${{ github.ref == 'preprod' && github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref}} 
      - run: echo The PR was merged
      - run: ls ${{ github.workspace }}