on:
  pull_request:
    types:
      - pushed
    branches:
      - preprod

jobs:
  preprod-deploy:
    if: ${{ github.ref == 'preprod' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was merged
      - run: ls ${{ github.workspace }}